### ISSUE TITLE
Title options are not visible in latest master version

### ISSUE THREAD

**Issue by thekalinga** [andrepolischuk/hyper-one-light#10]
Application title, minimise, restore, maximise icons & the left top dropdown are not visible once migrating to this theme

**Comment by iamstarkov** [comment]
Sorry, I'm using latest Hyper and later Hyper-one-light. Cant repoduce
![screen shot 2016-12-11 at 2 03 41 am](https://cloud.githubusercontent.com/assets/559321/21077255/25a45520-bf46-11e6-8645-255f2b74e61b.png)

**Comment by thekalinga** [comment]
I'm facing this issue in Ubuntu 14.04.

My bad, should have mentioned in the issue itself

**Comment by iamstarkov** [comment]
> latest master version

what do you mean? are you building hyper from source code?

**Comment by thekalinga** [comment]
Yes I built from source and installed latest version earlier.

Now, I installed 1.0.0 of hyper, the app itself is not coming up now.

Will post update once I can get the app to start

Thanks

**Comment by iamstarkov** [comment]
tried today with hyper v1, seems to work just fine. although vibrancy messes things up

**Comment by iamstarkov** [comment]
@thekalinga sup, can you reproduce an issue?

**Comment by thekalinga** [comment]
Hi,

Sorry.. Waiting for a new release from hyper. Can u place this on hold for now, please.

**Comment by iamstarkov** [comment]
1.0 has been released already

**Comment by iamstarkov** [comment]
lets do it this way. i'll close it for now, when you would have time, try to repro it. then if there is an error, i would want you to reopen this issue.

**Comment by iamstarkov** [comment]
if there is a bug, we just need more info

**Comment by finnzeit** [comment]
This happens on Windows 10 too
![title-issue](https://user-images.githubusercontent.com/17877082/27510474-3ce5e85e-593b-11e7-8e6a-89c79f127041.JPG)

**Comment by andrepolischuk** [comment]
@finnzeit @thekalinga I think I fixed this. Published as v1.1.4
