### ISSUE TITLE
vibrancy support

### ISSUE THREAD

**Issue by iamstarkov** [andrepolischuk/hyper-one-light#11]
do we need it? if so, how will it look?

**Comment by andrepolischuk** [comment]
Can we use this as option?

**Comment by andrepolischuk** [comment]
For example with `medium-light` vibrancy

<img width="782" alt="screen shot 2016-12-13 at 17 18 40" src="https://cloud.githubusercontent.com/assets/8956796/21143546/39bb136e-c158-11e6-9013-4c208656265c.png">

**Comment by iamstarkov** [comment]
thats good

**Comment by iamstarkov** [comment]
can it be done as a separate broad package as hyper-simple-highlight-active-session?
