### ISSUE TITLE
Problems with styles

### ISSUE THREAD

**Issue by felipemrodrigues** [andrepolischuk/hyper-one-light#13]
I don't know why but my Hyper with hyper-one-light is not like the readme screenshot.

![image](https://cloud.githubusercontent.com/assets/2872870/21167162/ac354570-c191-11e6-80c4-08b508ae6bf0.png)

**Comment by andrepolischuk** [comment]
I use zsh shell with [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting) plugin and custom prompt [neat](https://github.com/andrepolischuk/neat) in screenshot.

**Comment by felipemrodrigues** [comment]
Thanks @andrepolischuk
